### ISSUE TITLE
Making it easier to select language

### ISSUE THREAD

**Issue by xbony2** [4gray/oversetter#2]
![screen shot 2017-08-07 at 5 31 08 pm](https://user-images.githubusercontent.com/5623501/29046650-6614f74c-7b96-11e7-8dc9-9566b78f3fd6.png)

You can probably see how it might be a bit of a pain to select the base language and the language you want translated to, since the list is longer than my monitor (Good for Yandex, bad for me :P). Having a lil search bar and maybe having most-used (per user) languages at the top might be a good solution.

Cool app btw, I suspect I will be using it a lot.

**Comment by 4gray** [comment]
@xbony2 Thank you for your feedback and suggestions. I will try to implement both of the functions  in the next versions :-)

**Comment by gingerbeardman** [comment]
If you open the dropdown you can simply start to type the first letter of whichever language you desire and it will be selected. This is a macOS feature.

It would work even better if the languages in the dropdown were sorted in alphabetical order, as then you could type more than the first character.

**Comment by 4gray** [comment]
Closed with the release of v.0.3
