### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by gingerbeardman** [4gray/oversetter#7]
Using 0.3

<img width="420" alt="Screen Shot 2019-03-13 at 20 11 44" src="https://user-images.githubusercontent.com/49612/54311414-6b753880-45cc-11e9-8758-9ecc870786d3.png">

**Comment by 4gray** [comment]
Do you still have the same problem or it have been solved after resetting/re-entering of the API key?

**Comment by gingerbeardman** [comment]
Yes

**Comment by gingerbeardman** [comment]
Closed as fixed or not?

**Comment by 4gray** [comment]
> ~Closed as fixed or not?~
> 
> Thanks for fixing

Fixed in v0.3.1 https://github.com/4gray/oversetter/releases/tag/v0.3.1
